### ISSUE TITLE
405 not allowed

### ISSUE THREAD

**Issue by ruettet** [wbstack/api#424]
Hi,
I seem to have my connection up and running:
['https://osloddt.wiki.opencura.com/', 'Ruettet@vanderbot', 'XXXXXXXXXXXXXXXXXXXXXX']
{'batchcomplete': '', 'query': {'tokens': {'logintoken': 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+\\'}}}
{'login': {'result': 'Success', 'lguserid': 1, 'lgusername': 'Ruettet'}}

But a simple request from the API returns a 405 not allowed, even for a simple query: 
select distinct ?id ?string where {
      ?id ?label ?string.
      filter(lang(?string)="nl")
      }
      LIMIT 50

The return information is:

Traceback (most recent call last):
  File "vanderbot.py", line 1262, in <module>
    labelsAtWikidata = searchLabelsDescriptionsAtWikidata(qIds, 'label', labelLanguage)
  File "vanderbot.py", line 472, in searchLabelsDescriptionsAtWikidata
    data = r.json()
  File "C:\Users\Tom\PycharmProjects\osloddt\venv\lib\site-packages\requests\models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx/1.21.6</center>
</body>
</html>

Is anybody able to replicate the 405?

Thanks,
Tom

**Comment by toban** [comment]
Hello, thanks for the report. This looks like you are running a sparql query which wouldn't end up touching much from the api if anything. I wonder if this error could be related to the migration that at the time was on-going on wikibase.cloud. Are you still experiencing these errors?

**Comment by deer-wmde** [comment]
moved to phabricator: https://phabricator.wikimedia.org/T357056
