### ISSUE TITLE
JWT related production.ERROR: Implicit conversion of keys from strings is deprecated

### ISSUE THREAD

**Issue by addshore** [wbstack/api#9]
When deploying 1.2 on wbstack production.

Diff between what was deployed
- api code https://github.com/wbstack/api/compare/6x-1.1...6x-1.2
- deploy code https://github.com/wbstack/deploy/compare/6317100239d4a32352de92e1dcb747bb2b723ef0...main

```
[2020-12-10 11:22:09] production.ERROR: Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. {"exception":"[object] (ErrorException(code: 0): Implicit conversion of keys from strings is deprecated. Please use InMemory or LocalFileReference classes. at /var/www/html/vendor/lcobucci/jwt/src/Signer/BaseSigner.php:57)
[stacktrace]
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(16384, 'Implicit conver...', '/var/www/html/v...', 57, Array)
#1 /var/www/html/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(57): trigger_error('Implicit conver...', 16384)
#2 /var/www/html/vendor/lcobucci/jwt/src/Signer/BaseSigner.php(46): Lcobucci\\JWT\\Signer\\BaseSigner->getKey('file:///tmp/f7a...')
#3 /var/www/html/vendor/lcobucci/jwt/src/Signature.php(60): Lcobucci\\JWT\\Signer\\BaseSigner->verify('N=Y@\\xC15\\x8B\"\\x9F\\\\\\x99\\xDB\\xC01@...', 'XXX...', 'file:///tmp/f7a...')
#4 /var/www/html/vendor/lcobucci/jwt/src/Token.php(258): Lcobucci\\JWT\\Signature->verify(Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), 'XXX...', 'file:///tmp/f7a...')
#5 /var/www/html/vendor/league/oauth2-server/src/AuthorizationValidators/BearerTokenValidator.php(72): Lcobucci\\JWT\\Token->verify(Object(Lcobucci\\JWT\\Signer\\Rsa\\Sha256), 'file:///tmp/f7a...')
#6 /var/www/html/vendor/league/oauth2-server/src/ResourceServer.php(84): League\\OAuth2\\Server\\AuthorizationValidators\\BearerTokenValidator->validateAuthorization(Object(Zend\\Diactoros\\ServerRequest))
#7 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(175): League\\OAuth2\\Server\\ResourceServer->validateAuthenticatedRequest(Object(Zend\\Diactoros\\ServerRequest))
#8 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(127): Laravel\\Passport\\Guards\\TokenGuard->getPsrRequestViaBearerToken(Object(Illuminate\\Http\\Request))
#9 /var/www/html/vendor/laravel/passport/src/Guards/TokenGuard.php(90): Laravel\\Passport\\Guards\\TokenGuard->authenticateViaBearerToken(Object(Illuminate\\Http\\Request))
#10 /var/www/html/vendor/laravel/passport/src/PassportServiceProvider.php(275): Laravel\\Passport\\Guards\\TokenGuard->user(Object(Illuminate\\Http\\Request))
#11 [internal function]: Laravel\\Passport\\PassportServiceProvider->Laravel\\Passport\\{closure}(Object(Illuminate\\Http\\Request), NULL)
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/RequestGuard.php(58): call_user_func(Object(Closure), Object(Illuminate\\Http\\Request), NULL)
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/GuardHelpers.php(60): Illuminate\\Auth\\RequestGuard->user()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(62): Illuminate\\Auth\\RequestGuard->check()
#15 /var/www/html/app/Http/Middleware/Authenticate.php(15): Illuminate\\Auth\\Middleware\\Authenticate->authenticate(Object(Illuminate\\Http\\Request), Array)
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): App\\Http\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure), 'api')
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#24 /var/www/html/vendor/spatie/laravel-cors/src/Cors.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Spatie\\Cors\\Cors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#29 /var/www/html/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#30 {main}
"}
 - - [10/Dec/2020:11:22:09 +0000] "POST /wiki/mine HTTP/1.1" 500 
```

**Comment by addshore** [comment]
So some composer packages seemed to change:

- [lcobucci/jwt 3.3.1 -> 3.4.2](https://github.com/wbstack/api/compare/6x-1.1...6x-1.2#diff-f37acfaa6b11f575a9a6f41a75fa73a61d0f8ebc2c9b8cddc215d8aca10e44f5L1876)

https://stackoverflow.com/a/65009290/4746236

Solution, downgrade jwt from 3.4 to 3.3
